import type { Inspection, Product, Violation } from './types';

export const mockViolations: Violation[] = [
  {
    id: 'V-01',
    title: 'Non-Standard Metric Unit Abbreviation ("gms")',
    severity: 'High',
    description: 'Rule 11 strictly mandates the standard metric symbol "g". Abbreviation "gms" is non-compliant.',
    rule: 'Rule 11 & Rule 12, Legal Metrology Rules, 2011',
  },
  {
    id: 'V-02',
    title: 'Missing Unit Sale Price (USP)',
    severity: 'High',
    description: 'Statutory 2022 amendment requires per-gram/per-milliliter declaration alongside MRP.',
    rule: 'Rule 6(11), Legal Metrology Amendment Rules, 2022',
  },
  {
    id: 'V-03',
    title: 'Sub-Standard Font Size on PDP',
    severity: 'Medium',
    description: 'Measured font height 1.2 mm falls below mandated 2.0 mm threshold for this package size.',
    rule: 'Rule 9 & Second Schedule, Table 1',
  },
];

export const mockInspections: Inspection[] = [
  {
    id: 'INS-2024-PARLEG',
    product: 'Parle-G Original Gluco Biscuits',
    manufacturer: 'Parle Products Pvt. Ltd., Vile Parle East, Mumbai 400057',
    date: '02 Sep 2026',
    score: 96,
    status: 'COMPLIANT',
    inspector: 'Priya Sharma',
    category: 'Food & Beverages',
    declarations: [
      { label: 'Commodity Generic Name', value: 'Glucose Biscuits', confidence: 99 },
      { label: 'Manufacturer & Packer', value: 'Parle Products Pvt. Ltd., Mumbai 400057', confidence: 97 },
      { label: 'Net Quantity', value: '130 g', confidence: 99 },
      { label: 'Maximum Retail Price (MRP)', value: '₹ 10.00 (incl. of all taxes)', confidence: 98 },
      { label: 'Unit Sale Price (USP)', value: '₹ 0.077 / g', confidence: 94 },
      { label: 'Month & Year of Packing', value: '08/2026', confidence: 96 },
      { label: 'Consumer Care Helpline', value: '1800-227-774 & customercare@parle.biz', confidence: 95 },
    ],
    checks: [
      {
        requirement: 'Rule 6(1)(a) Manufacturer Details',
        detectedValue: 'Parle Products Pvt. Ltd., Mumbai',
        status: 'PASS',
        explanation: 'Full registered address and PIN code verified.',
      },
      {
        requirement: 'Rule 6(1)(c) Net Quantity Declaration',
        detectedValue: '130 g',
        status: 'PASS',
        explanation: 'Standard metric symbol "g" used. Letter height 4.1mm exceeds 4.0mm requirement.',
      },
      {
        requirement: 'Rule 6(1)(e) Maximum Retail Price',
        detectedValue: '₹ 10.00 (incl. of all taxes)',
        status: 'PASS',
        explanation: 'Indian Rupee symbol and tax inclusive clause verified.',
      },
      {
        requirement: 'Rule 6(11) Unit Sale Price (USP)',
        detectedValue: '₹ 0.077 / g',
        status: 'PASS',
        explanation: 'Unit rate per gram declared in compliance with 2022 amendment.',
      },
      {
        requirement: 'Rule 6(1)(l) Consumer Care Details',
        detectedValue: '1800-227-774 & customercare@parle.biz',
        status: 'PASS',
        explanation: 'Both telephone and official email address detected.',
      },
    ],
    violations: [],
  },
  {
    id: 'INS-2024-KURKURE',
    product: 'Kurkure Masala Munch Crisps',
    manufacturer: 'PepsiCo India Holdings Pvt. Ltd., Sangrur 148106, Punjab',
    date: '01 Sep 2026',
    score: 93,
    status: 'COMPLIANT',
    inspector: 'Priya Sharma',
    category: 'Food & Beverages',
    declarations: [
      { label: 'Generic Name', value: 'Extruded Savory Snack', confidence: 97 },
      { label: 'Manufacturer', value: 'PepsiCo India Holdings, Sangrur 148106', confidence: 96 },
      { label: 'Net Quantity', value: '75 g', confidence: 99 },
      { label: 'MRP', value: '₹ 20.00 (incl. of all taxes)', confidence: 97 },
      { label: 'Unit Sale Price', value: '₹ 0.267 / g', confidence: 92 },
      { label: 'Packing Date', value: '08/2026', confidence: 94 },
      { label: 'Consumer Helpline', value: '1800-22-4020 & feedback@pepsico.com', confidence: 95 },
    ],
    checks: [
      {
        requirement: 'Rule 6(1)(a) Manufacturer Identification',
        detectedValue: 'PepsiCo India Holdings, Sangrur 148106',
        status: 'PASS',
        explanation: 'Full plant and office address identified.',
      },
      {
        requirement: 'Rule 6(1)(c) Net Quantity Standard Unit',
        detectedValue: '75 g',
        status: 'PASS',
        explanation: 'Metric symbol "g" used with compliant 2.8mm numeral height.',
      },
      {
        requirement: 'Rule 6(1)(e) Maximum Retail Price',
        detectedValue: '₹ 20.00 (incl. of all taxes)',
        status: 'PASS',
        explanation: 'Pre-printed MRP with tax inclusivity clause.',
      },
    ],
    violations: [],
  },
  {
    id: 'INS-2024-AMULBTR',
    product: 'Amul Pasteurized Butter (500g)',
    manufacturer: 'GCMMF Ltd., Amul Dairy Road, Anand 388001, Gujarat',
    date: '31 Aug 2026',
    score: 98,
    status: 'COMPLIANT',
    inspector: 'Rohan Mehta',
    category: 'Food & Beverages',
    declarations: [
      { label: 'Generic Name', value: 'Pasteurized Butter', confidence: 99 },
      { label: 'Marketer', value: 'GCMMF Ltd., Anand 388001', confidence: 98 },
      { label: 'Net Quantity', value: '500 g', confidence: 99 },
      { label: 'MRP', value: '₹ 275.00 (incl. of all taxes)', confidence: 99 },
      { label: 'USP', value: '₹ 0.55 / g', confidence: 95 },
    ],
    checks: [
      {
        requirement: 'Rule 6(1)(a) Marketer & Packer',
        detectedValue: 'GCMMF Ltd., Anand 388001',
        status: 'PASS',
        explanation: 'Authorized apex cooperative declaration verified.',
      },
      {
        requirement: 'Rule 6(1)(c) Net Quantity Metric Size',
        detectedValue: '500 g',
        status: 'PASS',
        explanation: 'Standard weight declaration with font height of 4.6mm (> 4.0mm requirement).',
      },
    ],
    violations: [],
  },
  {
    id: 'INS-2024-SPICES',
    product: 'DesiZaika Garam Masala Pouch',
    manufacturer: 'Local Agro Spice Packers, Sonipat, Haryana',
    date: '30 Aug 2026',
    score: 52,
    status: 'VIOLATION',
    inspector: 'Priya Sharma',
    category: 'Food & Beverages',
    declarations: [
      { label: 'Product Name', value: 'DesiZaika Garam Masala', confidence: 92 },
      { label: 'Manufacturer', value: 'Local Agro Spice Packers, Sonipat', confidence: 85 },
      { label: 'Net Quantity', value: '100 gms', confidence: 94 },
      { label: 'MRP', value: 'Rs. 65/-', confidence: 82 },
      { label: 'Consumer Care', value: 'Phone only, no email', confidence: 78 },
    ],
    checks: [
      {
        requirement: 'Rule 6(1)(c) Standard Metric Unit',
        detectedValue: '100 gms',
        status: 'FAIL',
        explanation: 'Uses non-standard abbreviation "gms" instead of prescribed "g".',
      },
      {
        requirement: 'Rule 6(11) Unit Sale Price (USP)',
        detectedValue: 'Missing',
        status: 'FAIL',
        explanation: 'Failed to declare Unit Sale Price required under 2022 amendment.',
      },
    ],
    violations: mockViolations,
  },
];

export const mockProducts: Product[] = [
  {
    id: 'PRD-1',
    name: 'Parle-G Original Gluco Biscuits (130g)',
    brand: 'Parle',
    manufacturer: 'Parle Products Pvt. Ltd.',
    category: 'Food & Beverages',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&auto=format&fit=crop&q=80',
    lastInspection: '02 Sep 2026',
    status: 'COMPLIANT',
    violations: 0,
  },
  {
    id: 'PRD-2',
    name: 'Kurkure Masala Munch Crisps (75g)',
    brand: 'Kurkure',
    manufacturer: 'PepsiCo India Holdings',
    category: 'Food & Beverages',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&auto=format&fit=crop&q=80',
    lastInspection: '01 Sep 2026',
    status: 'COMPLIANT',
    violations: 0,
  },
  {
    id: 'PRD-3',
    name: 'Amul Pasteurized Butter (500g)',
    brand: 'Amul',
    manufacturer: 'GCMMF Ltd., Anand',
    category: 'Dairy & Refrigerated',
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400&auto=format&fit=crop&q=80',
    lastInspection: '31 Aug 2026',
    status: 'COMPLIANT',
    violations: 0,
  },
  {
    id: 'PRD-4',
    name: 'DesiZaika Garam Masala Pouch (100g)',
    brand: 'DesiZaika',
    manufacturer: 'Local Agro Spice Packers',
    category: 'Food & Beverages',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&auto=format&fit=crop&q=80',
    lastInspection: '30 Aug 2026',
    status: 'VIOLATION',
    violations: 3,
  },
];

export const samplePackages = [
  {
    id: 'sample-1',
    name: 'Parle-G Gluco Biscuits (130g)',
    category: 'Food & Beverages',
    uri: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&auto=format&fit=crop&q=80',
    inspectionId: 'INS-2024-PARLEG',
  },
  {
    id: 'sample-2',
    name: 'Kurkure Masala Munch (75g)',
    category: 'Food & Beverages',
    uri: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&auto=format&fit=crop&q=80',
    inspectionId: 'INS-2024-KURKURE',
  },
  {
    id: 'sample-3',
    name: 'Amul Pasteurized Butter (500g)',
    category: 'Dairy & Refrigerated',
    uri: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&auto=format&fit=crop&q=80',
    inspectionId: 'INS-2024-AMULBTR',
  },
  {
    id: 'sample-4',
    name: 'DesiZaika Spices Pouch (Non-Compliant)',
    category: 'Food & Beverages',
    uri: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',
    inspectionId: 'INS-2024-SPICES',
  },
];

export const liveActivity = [
  {
    id: 'act-1',
    product: 'Parle-G Original Gluco Biscuits',
    officer: 'Priya Sharma',
    time: '4m ago',
    action: 'Audited & Certified',
    status: 'COMPLIANT' as const,
  },
  {
    id: 'act-2',
    product: 'Kurkure Masala Munch Crisps',
    officer: 'Rohan Mehta',
    time: '18m ago',
    action: 'Verified USP',
    status: 'COMPLIANT' as const,
  },
  {
    id: 'act-3',
    product: 'DesiZaika Garam Masala Pouch',
    officer: 'Vikram Singh',
    time: '42m ago',
    action: 'Flagged Rule 11/12 Violation',
    status: 'VIOLATION' as const,
  },
];

export const commonViolations = [
  { rule: 'Rule 11 & 12', title: 'Non-Standard Metric Units ("gms")', severity: 'High' as const, pct: 38 },
  { rule: 'Rule 6(11)', title: 'Missing Unit Sale Price (USP)', severity: 'High' as const, pct: 28 },
  { rule: 'Rule 9', title: 'Sub-standard Numeral Font Height', severity: 'Medium' as const, pct: 19 },
  { rule: 'Rule 6(1)(l)', title: 'Incomplete Consumer Helpline Details', severity: 'Low' as const, pct: 15 },
];
